small fixes, adding spatial search attributes latitude and longitude
pro-vision/pv-entitygenerator pull request #10
Opened 2022-06-22 14:08 UTC by sschlick

here some small fixes as well as logitude/latitude search attributes

2022-06-23 10:05 UTC, stefanseifert requested changes

2022-06-23 10:05 UTC, stefanseifert commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +        <xsl:text>de.vivento.koop.util.IdEnum</xsl:text>
please do not reference project-specific code here.

2022-06-23 10:05 UTC, stefanseifert commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +    typeClass=de.vivento.koop.jpa.XmlMappingUserType.class,
please do not reference project-specific code here.

2022-06-23 10:05 UTC, stefanseifert commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +  public static class Converter extends de.vivento.koop.jpa.converter.WLConverter&lt;</xsl:text><xsl:value-of select="$entity"/><xsl:text>&gt; {
please do not reference project-specific code here.

2022-07-06 10:30 UTC, sschlick commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +        <xsl:text>de.vivento.koop.util.IdEnum</xsl:text>
ok, I removed project-specific references with commit ebc8995

2022-07-06 10:30 UTC, sschlick commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +    typeClass=de.vivento.koop.jpa.XmlMappingUserType.class,
ok, I removed project-specific references with commit ebc8995

2022-07-06 10:30 UTC, sschlick commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +  public static class Converter extends de.vivento.koop.jpa.converter.WLConverter&lt;</xsl:text><xsl:value-of select="$entity"/><xsl:text>&gt; {
ok, I removed project-specific references with commit ebc8995

2022-07-12 14:13 UTC, stefanseifert commented on PVEntityGenerator/xml/Platform_Java11JPA/entity_entity-class.xsl
> +  public static class Converter implements javax.persistence.AttributeConverter&lt;</xsl:text><xsl:value-of select="$entity"/>, Integer<xsl:text>&gt; {
please use english language for comment

does this inner class need to be public? if possible, use default scope instead to not "pollute" the list of public classes in the project.

2022-07-12 14:13 UTC, stefanseifert commented on PVEntityGenerator/xml/Platform_Java11JPA/platform.xml
> +		  <parameter-definition
this is a duplicate of the entry before?

2022-07-13 07:38 UTC, stefanseifert approved these changes
thanks!

2022-07-13 07:38 UTC, merged